name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      USING_COVERAGE: '3.9'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install -r ./requirements.txt  
      - name: Compile
        run: |
          python -m nuitka --onefile --standalone --follow-imports --assume-yes-for-downloads --windows-company-name=JKinc --windows-product-name="Element Sound Fixer" --windows-product-version=v1.0.0 --windows-icon-from-ico=icon.ico main.py  
          move main.exe win64.exe 
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "win64.exe"
          bodyFile: "README.md"
          allowUpdates: true
          tag: "v1.0.0"
          draft: true
          makeLatest: true
