name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      USING_COVERAGE: '3.9'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install -r ./requirements.txt  
      - name: Compile
        run: |
          python -m nuitka --onefile --standalone --follow-imports --assume-yes-for-downloads --windows-company-name=JKinc --windows-product-name="Element Sound Fixer" --windows-product-version=${{ github.event.head_commit.message }} --windows-icon-from-ico=icon.ico main.py  
          move main.exe patcher.exe 
      - name: Compress
        run: |
          Get-ChildItem -Path patcher.exe, instructions.txt |
          Compress-Archive -DestinationPath release.zip
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          bodyFile: "README.md"
          allowUpdates: true
          tag: "v${{ github.event.head_commit.message }}"
          draft: true
          makeLatest: true
